"""Run the bounded HUP138 scalp-only bilateral F3/F4 3B sensitivity.

This runner intentionally does not enter the paired scalp/iEEG result tables.
It uses the locked HUP RR/stage arrays and the existing two-channel RR-domain
estimator, but it makes no iEEG, group, inferential, behavioural, or LC claim.

The private HUP138 sidecar must first be regenerated under the current
outcome-neutral F3/F4 acquisition plan. No public artifacts are generated by
tests or by importing this module.
"""
from __future__ import annotations

import argparse
import csv
import hashlib
import json
import os
import tempfile

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

from artifact_contracts import SCALP_F3_F4_EXPLORATORY_SCHEMA
from event_3B_cached import stable_stage_epoch_indices, stage_so_times
from event_3b_estimators import FS_RR, rr_baseline_hr, subject_so_triggered
from materialize_qc_cache import materialize
from pipeline_version import (
    ANALYSIS_VERSION,
    CACHE_SCHEMA_VERSION,
    atomic_json_dump,
    file_sha256,
    git_is_dirty,
    git_revision,
    npz_scalar_text,
    runtime_versions,
    source_tree_sha256,
    utc_now,
)
from qc_profiles import (
    load_qc_profile,
    profile_file_sha256,
    qc_profile_sha256,
)
from staging_helpers import EPOCH


ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SUBJECT = "HUP138_phaseII"
PIPELINE = "scalp_f3_f4_exploratory"
RESULT_SCHEMA = SCALP_F3_F4_EXPLORATORY_SCHEMA
PROFILE_ID = "overlap11_endpoint_local"
DEFAULT_IEEG_CACHE = os.path.join(
    ROOT, "data", "derived", "lc_infraslow")
DEFAULT_SCALP_CACHE = os.path.join(
    ROOT, "data", "derived", "paired_scalp")
DEFAULT_QC_GRID = os.path.join(
    ROOT, "outputs", "qc_grid_public", "locked",
    "overlap11_endpoint_local__hup.json")
DEFAULT_SCALP_INVENTORY = os.path.join(
    ROOT, "outputs", "paired_scalp_inventory",
    "hup_scalp_channel_inventory.json")
STAGES = ("N2", "N3", "NREM")
ROLES = ("f3", "f4")
N_SURROGATES = 199
DEFAULT_OUTPUT = os.path.join(
    ROOT, "outputs", "scalp_f3_f4_exploratory")
RESULT_JSON = "HUP138_phaseII_bilateral_3B.json"
RESULT_CSV = "HUP138_phaseII_bilateral_3B.csv"
RESULT_PNG = "HUP138_phaseII_bilateral_3B.png"
RESULT_SVG = "HUP138_phaseII_bilateral_3B.svg"
RESULT_FILES = (RESULT_JSON, RESULT_CSV, RESULT_PNG, RESULT_SVG)
MANIFEST_FIELDS = frozenset({
    "schema_version",
    "pipeline",
    "run_state",
    "analysis_version",
    "cache_schema_version",
    "generated_at_utc",
    "code_revision",
    "code_dirty",
    "source_tree_sha256",
    "runtime_versions",
    "subject",
    "analysis_scope",
    "paired_comparison_performed",
    "group_inference_performed",
    "input_lineage",
    "result_files_sha256",
})
RESULT_FIELDS = frozenset({
    "schema_version",
    "pipeline",
    "analysis_version",
    "cache_schema_version",
    "subject",
    "analysis_scope",
    "exploratory",
    "paired_comparison_performed",
    "group_inference_performed",
    "event_locking_inference_available",
    "provenance",
    "input_lineage",
    "method",
    "locked_ieeg_context",
    "result",
    "claim_limits",
})
INPUT_LINEAGE_FIELDS = frozenset({
    "inventory_path_relative",
    "inventory_sha256",
    "inventory_manifest_path_relative",
    "inventory_manifest_sha256",
    "qc_grid_path_relative",
    "qc_grid_sha256",
    "qc_grid_profile_sha256",
    "ieeg_cache_path_relative",
    "ieeg_cache_sha256",
    "ieeg_cache_manifest_path_relative",
    "ieeg_cache_manifest_sha256",
    "ieeg_cache_manifest_run_id",
    "scalp_sidecar_path_relative",
    "scalp_sidecar_sha256",
    "scalp_sidecar_manifest_path_relative",
    "scalp_sidecar_manifest_sha256",
    "scalp_sidecar_cache_dependency_sha256",
    "validated_sidecar_roles",
    "portal_source_identity",
    "inventory_channel_identity",
    "rr_4_sha256",
    "stage_lab_sha256",
    "rr_4_n_samples",
    "stage_lab_n_epochs",
    "channel_roles_json_sha256",
    "source_identity_json_sha256",
})
CSV_FIELDS = (
    "subject",
    "analysis_scope",
    "stage",
    "stage_interpretation",
    "pooled_nrem_exploratory",
    "available",
    "unavailability_reason",
    "f3_channel",
    "f4_channel",
    "f3_nonflat",
    "f4_nonflat",
    "raw_stage_epochs",
    "stable_stage_epochs",
    "finite_stage_rr_samples",
    "f3_eligible_so_count",
    "f4_eligible_so_count",
    "f3_peak_lag_s",
    "f4_peak_lag_s",
    "bilateral_peak_lag_s",
    "pct_above_stage_mean",
    "event_locked_local_change_pct",
    "event_locking_z",
    "event_locking_p",
)


def _json_safe(value):
    if isinstance(value, dict):
        return {str(key): _json_safe(item) for key, item in value.items()}
    if isinstance(value, (list, tuple)):
        return [_json_safe(item) for item in value]
    if isinstance(value, np.ndarray):
        return _json_safe(value.tolist())
    if isinstance(value, np.generic):
        return _json_safe(value.item())
    if isinstance(value, float) and not np.isfinite(value):
        return None
    return value


def _canonical_json(value):
    return json.dumps(
        _json_safe(value),
        sort_keys=True,
        separators=(",", ":"),
        allow_nan=False,
    )


def _sha256_bytes(value):
    return hashlib.sha256(value).hexdigest()


def _array_sha256(value):
    array = np.ascontiguousarray(np.asarray(value))
    digest = hashlib.sha256()
    digest.update(array.dtype.str.encode("ascii"))
    digest.update(b"\0")
    digest.update(str(array.shape).encode("ascii"))
    digest.update(b"\0")
    digest.update(array.tobytes())
    return digest.hexdigest()


def _stage_seed(stage):
    token = (
        f"{PIPELINE}|{SUBJECT}|{stage}|"
        "bilateral-scalp-rr-stage-shift-diagnostic|v1"
    )
    return int.from_bytes(
        hashlib.sha256(token.encode("utf-8")).digest()[:4],
        "little",
    )


def _stage_epochs(labels, stage):
    labels = np.asarray(labels).astype(str)
    if stage == "NREM":
        pooled = np.where(
            np.isin(labels, ("NREM", "N2", "N3")), "NREM", "")
        return (
            stable_stage_epoch_indices(pooled, "NREM"),
            int(np.isin(labels, ("NREM", "N2", "N3")).sum()),
        )
    return (
        stable_stage_epoch_indices(labels, stage),
        int((labels == stage).sum()),
    )


def _stage_pool(rr, epochs):
    mask = np.zeros(len(rr), bool)
    for epoch in epochs:
        start = int(epoch * EPOCH * FS_RR)
        stop = int((epoch + 1) * EPOCH * FS_RR)
        mask[start:stop] = True
    return np.where(mask & np.isfinite(rr))[0]


def _stage_interpretation(stage):
    if stage == "N2":
        return "HUP proxy N2-like; not R&K Stage 2"
    if stage == "N3":
        return "HUP proxy N3-like; not R&K SWS"
    return "pooled NREM sensitivity; no Naji stage counterpart"


def _analyse_bilateral(scalp, base, profile):
    """Return one joint F3/F4 scalp-only result using frozen 3B gates."""
    roles = json.loads(npz_scalar_text(scalp, "channel_roles_json"))
    missing = [role for role in ROLES if role not in roles]
    if missing:
        raise RuntimeError(
            f"{SUBJECT} sidecar lacks required bilateral roles {missing}")
    channels = [str(value) for value in scalp["scalp_chans"]]
    role_channels = {role: str(roles[role]) for role in ROLES}
    if len(set(role_channels.values())) != 2:
        raise RuntimeError("F3 and F4 must resolve to two distinct channels")
    nonflat_mask = np.asarray(
        scalp["scalp_signal_nonflat_mask"], bool).ravel()
    if len(nonflat_mask) != len(channels):
        raise RuntimeError("scalp activity mask does not align with channels")
    nonflat = {
        role: bool(nonflat_mask[channels.index(channel)])
        for role, channel in role_channels.items()
    }
    rr = np.asarray(base["rr_4"], float)
    labels = np.asarray(base["stage_lab"]).astype(str)
    endpoint = profile["endpoint_3b"]
    if int(endpoint["minimum_contacts"]) != 2:
        raise RuntimeError("locked 3B profile no longer requires two channels")

    stages = {}
    for stage in STAGES:
        stable, raw_epochs = _stage_epochs(labels, stage)
        pool = _stage_pool(rr, stable)
        keep = set(stable.tolist())
        event_times = {
            role: stage_so_times(
                scalp,
                channel,
                keep,
                percentile=float(endpoint["so_amplitude_percentile"]),
            )
            for role, channel in role_channels.items()
        }
        reasons = []
        for role in ROLES:
            if not nonflat[role]:
                reasons.append(f"{role.upper()} is numerically flat")
        if not bool(base.get("hr_meets_profile", False)):
            reasons.append("cardiac coverage below locked profile")
        finite_rr = int(np.isfinite(rr).sum())
        if finite_rr < int(endpoint["minimum_finite_rr_samples"]):
            reasons.append(
                f"{finite_rr} finite RR samples < "
                f"{endpoint['minimum_finite_rr_samples']}")
        if len(stable) < 6:
            reasons.append("no uninterrupted 180-s stage run")
        if len(pool) < int(endpoint["minimum_finite_stage_samples"]):
            reasons.append(
                f"{len(pool)} finite stage samples < "
                f"{endpoint['minimum_finite_stage_samples']}")
        for role in ROLES:
            count = len(event_times[role])
            if count < int(endpoint["minimum_so_per_contact"]):
                reasons.append(
                    f"{role.upper()} {count} eligible SOs < "
                    f"{endpoint['minimum_so_per_contact']}")

        estimate = None
        if not reasons:
            baseline = rr_baseline_hr(rr[pool])
            estimate = subject_so_triggered(
                rr,
                [event_times[role] for role in ROLES],
                baseline,
                pool,
                n_sur=N_SURROGATES,
                rng=np.random.RandomState(_stage_seed(stage)),
                domain="rr",
                minimum_channels=2,
                channel_ids=[role_channels[role] for role in ROLES],
                minimum_events_per_channel=int(
                    endpoint["minimum_so_per_contact"]),
                minimum_surrogate_pool_samples=int(
                    endpoint["minimum_finite_stage_samples"]),
            )
            if estimate is None:
                reasons.append(
                    "complete in-stage RR windows leave insufficient "
                    "two-channel SO support")
            else:
                if (
                    estimate.get("n_channels") != 2
                    or estimate.get("z") is not None
                    or estimate.get("p_upper") is not None
                ):
                    raise RuntimeError(
                        "bilateral estimator violated its descriptive contract")
                estimate["stage_mean_hr"] = float(baseline)
                estimate["channel_peak_lag_by_role_s"] = {
                    role: float(value)
                    for role, value in zip(
                        ROLES, estimate["channel_peak_lag_s"])
                }

        stages[stage] = {
            "stage": stage,
            "stage_interpretation": _stage_interpretation(stage),
            "pooled_nrem_exploratory": stage == "NREM",
            "raw_epochs": raw_epochs,
            "stable_epochs": int(len(stable)),
            "stable_seconds": int(len(stable) * EPOCH),
            "finite_stage_rr_samples": int(len(pool)),
            "eligible_so_count_by_role": {
                role: int(len(event_times[role])) for role in ROLES
            },
            "so_amplitude_percentile": float(
                endpoint["so_amplitude_percentile"]),
            "so_amplitude_rule_provenance": (
                "within-sensor/stage percentile adaptation; not Naji's "
                "fixed referenced-scalp voltage criteria"),
            "available": estimate is not None,
            "support_reasons": reasons,
            "estimate": estimate,
        }
    return {
        "subject": SUBJECT,
        "analysis_scope": "participant_level_scalp_only",
        "exploratory": True,
        "roles": list(ROLES),
        "channels_by_role": role_channels,
        "sensor_nonflat_by_role": nonflat,
        "tachogram_domain": "rr",
        "minimum_channels": 2,
        "minimum_events_per_channel": int(
            endpoint["minimum_so_per_contact"]),
        "stages": stages,
    }


def _csv_rows(payload):
    result = payload["result"]
    rows = []
    for stage in STAGES:
        stage_result = result["stages"][stage]
        estimate = stage_result.get("estimate")
        peak_by_role = (
            {} if estimate is None
            else estimate.get("channel_peak_lag_by_role_s", {})
        )
        reasons = "; ".join(stage_result["support_reasons"]) or None
        rows.append({
            "subject": SUBJECT,
            "analysis_scope": result["analysis_scope"],
            "stage": stage,
            "stage_interpretation": stage_result[
                "stage_interpretation"],
            "pooled_nrem_exploratory": stage == "NREM",
            "available": estimate is not None,
            "unavailability_reason": (
                reasons if estimate is None else None),
            "f3_channel": result["channels_by_role"]["f3"],
            "f4_channel": result["channels_by_role"]["f4"],
            "f3_nonflat": result["sensor_nonflat_by_role"]["f3"],
            "f4_nonflat": result["sensor_nonflat_by_role"]["f4"],
            "raw_stage_epochs": stage_result["raw_epochs"],
            "stable_stage_epochs": stage_result["stable_epochs"],
            "finite_stage_rr_samples": stage_result[
                "finite_stage_rr_samples"],
            "f3_eligible_so_count": stage_result[
                "eligible_so_count_by_role"]["f3"],
            "f4_eligible_so_count": stage_result[
                "eligible_so_count_by_role"]["f4"],
            "f3_peak_lag_s": peak_by_role.get("f3"),
            "f4_peak_lag_s": peak_by_role.get("f4"),
            "bilateral_peak_lag_s": (
                None if estimate is None else estimate["peak_lag_s"]),
            "pct_above_stage_mean": (
                None if estimate is None
                else estimate["pct_above_stage_mean"]),
            "event_locked_local_change_pct": (
                None if estimate is None
                else estimate["event_locked_local_change_pct"]),
            "event_locking_z": None,
            "event_locking_p": None,
        })
    return rows


def _write_csv(path, rows):
    with open(path, "w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(
            handle, fieldnames=CSV_FIELDS, lineterminator="\n")
        writer.writeheader()
        writer.writerows(rows)


def _make_figure(payload, png_path, svg_path):
    result = payload["result"]
    with plt.rc_context({"svg.hashsalt": PIPELINE}):
        fig, axes = plt.subplots(
            1, 3, figsize=(13, 4.2), constrained_layout=True,
            sharey=True,
        )
        for axis, stage in zip(axes, STAGES):
            stage_result = result["stages"][stage]
            estimate = stage_result.get("estimate")
            if estimate is None:
                axis.text(
                    0.5,
                    0.55,
                    "Unavailable",
                    ha="center",
                    va="center",
                    transform=axis.transAxes,
                    fontsize=12,
                )
                axis.text(
                    0.5,
                    0.38,
                    "\n".join(stage_result["support_reasons"]),
                    ha="center",
                    va="center",
                    transform=axis.transAxes,
                    fontsize=7,
                    wrap=True,
                )
            else:
                axis.plot(
                    estimate["lag_s"],
                    estimate["curve"],
                    color="#2457A7",
                    linewidth=1.8,
                    label="mean F3/F4 RR curve → HR",
                )
                axis.axvline(
                    estimate["peak_lag_s"],
                    color="#B24A33",
                    linestyle="--",
                    linewidth=1.2,
                    label="mean electrode peak lag",
                )
                axis.legend(frameon=False, fontsize=7)
            axis.axvline(0, color="0.5", linewidth=0.8)
            axis.grid(alpha=0.2)
            axis.set_title(
                f"{stage}\n{stage_result['stage_interpretation']}",
                fontsize=9,
            )
            axis.set_xlabel("lag from SO trough (s)")
        axes[0].set_ylabel("heart rate (bpm)")
        fig.suptitle(
            "HUP138 bilateral scalp F3/F4 SO→HR sensitivity\n"
            "participant-level exploratory; descriptive only; "
            "unknown references; no paired/group/LC claim",
            fontsize=11,
        )
        stable_metadata = {
            "Title": "HUP138 bilateral scalp F3/F4 exploratory 3B",
            "Creator": "ieeg-human-lc-infraslow-3ABD",
            "Date": None,
        }
        fig.savefig(
            png_path,
            dpi=180,
            bbox_inches="tight",
            metadata=stable_metadata,
        )
        fig.savefig(
            svg_path,
            dpi=180,
            bbox_inches="tight",
            metadata=stable_metadata,
        )
        plt.close(fig)


def _write_artifacts(payload, output_dir):
    """Write deterministic result files, then atomically publish the manifest."""
    if payload.get("provenance", {}).get("code_dirty") is not False:
        raise RuntimeError(
            "publication requires a clean source tree; no artifacts written")
    if (
        set(payload) != RESULT_FIELDS
        or not isinstance(payload.get("input_lineage"), dict)
        or set(payload["input_lineage"]) != INPUT_LINEAGE_FIELDS
    ):
        raise RuntimeError(
            "publication payload has a nonexact schema; no artifacts written")
    output_dir = os.path.abspath(output_dir)
    os.makedirs(output_dir, exist_ok=True)
    with tempfile.TemporaryDirectory(
            prefix=".hup138-f3-f4-", dir=os.path.dirname(output_dir)) as work:
        atomic_json_dump(payload, os.path.join(work, RESULT_JSON))
        _write_csv(os.path.join(work, RESULT_CSV), _csv_rows(payload))
        _make_figure(
            payload,
            os.path.join(work, RESULT_PNG),
            os.path.join(work, RESULT_SVG),
        )
        hashes = {
            name: file_sha256(os.path.join(work, name))
            for name in RESULT_FILES
        }
        manifest = {
            "schema_version": RESULT_SCHEMA,
            "pipeline": PIPELINE,
            "run_state": "complete",
            "analysis_version": ANALYSIS_VERSION,
            "cache_schema_version": CACHE_SCHEMA_VERSION,
            "generated_at_utc": utc_now(),
            "code_revision": payload["provenance"]["code_revision"],
            "code_dirty": payload["provenance"]["code_dirty"],
            "source_tree_sha256": payload["provenance"][
                "source_tree_sha256"],
            "runtime_versions": payload["provenance"][
                "runtime_versions"],
            "subject": SUBJECT,
            "analysis_scope": "participant_level_scalp_only",
            "paired_comparison_performed": False,
            "group_inference_performed": False,
            "input_lineage": payload["input_lineage"],
            "result_files_sha256": hashes,
        }
        if set(manifest) != MANIFEST_FIELDS:
            raise RuntimeError("internal bilateral manifest schema is not exact")
        atomic_json_dump(manifest, os.path.join(work, "RUN_MANIFEST.json"))
        old_manifest = os.path.join(output_dir, "RUN_MANIFEST.json")
        if os.path.isfile(old_manifest):
            os.unlink(old_manifest)
        for name in (*RESULT_FILES, "RUN_MANIFEST.json"):
            os.replace(
                os.path.join(work, name),
                os.path.join(output_dir, name),
            )
    return manifest


def _inventory_subject_record(path):
    with open(path, encoding="utf-8") as handle:
        payload = json.load(handle)
    matching = [
        value for value in payload.get("subjects", [])
        if value.get("subject") == SUBJECT
    ]
    if len(matching) != 1:
        raise RuntimeError(
            f"inventory contains {len(matching)} {SUBJECT} records")
    return matching[0]


def build_payload(*, inventory_path, qc_grid_path, ieeg_cache_dir,
                  scalp_cache_dir):
    """Validate all private inputs and return the publishable result payload."""
    # Private cache validation is publication-only. Keeping these imports local
    # lets clean-checkout source tests exercise the estimator and artifact
    # contract without importing portal/cache producer code.
    from cache_paired_scalp import validate_pinned_ieeg_cache
    from paired_scalp_ieeg_comparison import (
        _load_frozen_profile_record,
        _validate_scalp_cache,
        _validate_scalp_inventory,
    )

    code_revision = git_revision(ROOT)
    code_dirty = git_is_dirty(ROOT)
    if code_dirty is not False:
        raise RuntimeError(
            "publication requires a clean source tree before private inputs "
            "are materialized")
    inventory_path = os.path.abspath(inventory_path)
    qc_grid_path = os.path.abspath(qc_grid_path)
    inventory_pin = _validate_scalp_inventory(
        inventory_path,
        qc_grid_path=qc_grid_path,
        ieeg_cache_dir=ieeg_cache_dir,
        scalp_cache_dir=scalp_cache_dir,
    )
    if SUBJECT not in inventory_pin[
            "participants_with_unique_f3_and_f4_labels"]:
        raise RuntimeError(
            f"audited inventory does not prove unique F3/F4 for {SUBJECT}")
    inventory_record = _inventory_subject_record(inventory_path)

    profile = load_qc_profile(PROFILE_ID)
    _, frozen_profile, frozen_subjects = _load_frozen_profile_record(
        qc_grid_path)
    if SUBJECT not in frozen_subjects:
        raise RuntimeError(f"{SUBJECT} is absent from the locked QC grid")
    pinned = validate_pinned_ieeg_cache(SUBJECT, ieeg_cache_dir)
    sidecar = _validate_scalp_cache(
        SUBJECT, os.path.abspath(scalp_cache_dir), pinned)
    if set(sidecar["roles"]) < set(ROLES):
        raise RuntimeError("validated terminal sidecar lacks F3/F4")

    with (
        np.load(pinned["path"], allow_pickle=False) as ieeg,
        np.load(sidecar["path"], allow_pickle=False) as scalp,
    ):
        base = materialize(ieeg, profile)
        result = _analyse_bilateral(scalp, base, profile)
        shared_hashes = {
            "rr_4_sha256": _array_sha256(base["rr_4"]),
            "stage_lab_sha256": _array_sha256(base["stage_lab"]),
            "rr_4_n_samples": int(len(base["rr_4"])),
            "stage_lab_n_epochs": int(len(base["stage_lab"])),
            "channel_roles_json_sha256": _sha256_bytes(
                npz_scalar_text(
                    scalp, "channel_roles_json").encode("utf-8")),
            "source_identity_json_sha256": _sha256_bytes(
                npz_scalar_text(
                    scalp, "source_identity_json").encode("utf-8")),
        }
        source_identity = json.loads(npz_scalar_text(
            scalp, "source_identity_json"))

    frozen_3b = frozen_subjects[SUBJECT].get("result_3b", {})
    available_ieeg_stages = [
        stage for stage in STAGES
        if bool(
            frozen_3b.get("stages", {}).get(
                stage, {}).get("available_under_profile")
        )
    ]
    payload = {
        "schema_version": RESULT_SCHEMA,
        "pipeline": PIPELINE,
        "analysis_version": ANALYSIS_VERSION,
        "cache_schema_version": CACHE_SCHEMA_VERSION,
        "subject": SUBJECT,
        "analysis_scope": "participant_level_scalp_only",
        "exploratory": True,
        "paired_comparison_performed": False,
        "group_inference_performed": False,
        "event_locking_inference_available": False,
        "provenance": {
            "code_revision": code_revision,
            "code_dirty": code_dirty,
            "source_tree_sha256": source_tree_sha256(ROOT),
            "runtime_versions": runtime_versions(),
        },
        "input_lineage": {
            "inventory_path_relative": os.path.relpath(
                inventory_path, ROOT).replace(os.sep, "/"),
            "inventory_sha256": file_sha256(inventory_path),
            "inventory_manifest_path_relative": inventory_pin[
                "manifest_path_relative"],
            "inventory_manifest_sha256": inventory_pin["manifest_sha256"],
            "qc_grid_path_relative": os.path.relpath(
                qc_grid_path, ROOT).replace(os.sep, "/"),
            "qc_grid_sha256": file_sha256(qc_grid_path),
            "qc_grid_profile_sha256": frozen_profile["qc_profile_sha256"],
            "ieeg_cache_path_relative": os.path.relpath(
                pinned["path"], ROOT).replace(os.sep, "/"),
            "ieeg_cache_sha256": pinned["sha256"],
            "ieeg_cache_manifest_path_relative": os.path.relpath(
                pinned["manifest_path"], ROOT).replace(os.sep, "/"),
            "ieeg_cache_manifest_sha256": pinned["manifest_sha256"],
            "ieeg_cache_manifest_run_id": pinned["manifest_run_id"],
            "scalp_sidecar_path_relative": os.path.relpath(
                sidecar["path"], ROOT).replace(os.sep, "/"),
            "scalp_sidecar_sha256": sidecar["sha256"],
            "scalp_sidecar_manifest_path_relative": os.path.relpath(
                sidecar["manifest_path"], ROOT).replace(os.sep, "/"),
            "scalp_sidecar_manifest_sha256": sidecar["manifest_sha256"],
            "scalp_sidecar_cache_dependency_sha256": sidecar[
                "cache_dependency_sha256"],
            "validated_sidecar_roles": dict(sidecar["roles"]),
            "portal_source_identity": source_identity,
            "inventory_channel_identity": {
                role: inventory_record["roles"][role]["matches"][0]
                for role in ROLES
            },
            **shared_hashes,
        },
        "method": {
            "source_profile_id": PROFILE_ID,
            "source_profile_sha256": qc_profile_sha256(profile),
            "source_profile_file_sha256": profile_file_sha256(),
            "estimator": "event_3b_estimators.subject_so_triggered",
            "tachogram_domain": "rr",
            "channels": ["F3", "F4"],
            "minimum_channels": 2,
            "n_surrogates_for_diagnostic_only": N_SURROGATES,
            "event_locking_z_p": None,
            "primary_descriptive_outputs": [
                "peak_lag_s",
                "channel_peak_lag_by_role_s",
                "pct_above_stage_mean",
            ],
            "secondary_descriptive_output": (
                "event_locked_local_change_pct"),
            "reference_status": (
                "portal online references are undocumented; F3/F4 labels do "
                "not establish Naji's F3/A2 and F4/A1 montage"),
            "aggregation": (
                "average the two electrode RR curves for magnitude; "
                "average electrode-specific post-trough RR-minimum/HR-maximum "
                "lags for bilateral timing"),
        },
        "locked_ieeg_context": {
            "available_3b_stages": available_ieeg_stages,
            "used_as_comparison_arm": False,
            "note": (
                "locked iEEG context is reported only to prove that this "
                "artifact does not manufacture a paired endpoint"),
        },
        "result": result,
        "claim_limits": [
            "not an exact Naji replication or montage",
            "N2/N3 are proxy labels, and pooled NREM has no Naji counterpart",
            (
                "automated ECG detection was not visually adjudicated as in "
                "Naji"
            ),
            (
                "PCHIP RR interpolation differs from the paper's piecewise "
                "cubic spline"
            ),
            (
                "within-stage percentile amplitude and repository duration "
                "gates are detector adaptations, not exact paper criteria"
            ),
            (
                "candidate artifact QC requires a clean trough sample, not a "
                "fully artifact-clean SO waveform"
            ),
            "no event-locking significance test",
            "no behavioural timing-performance test",
            "no scalp-versus-iEEG comparison or equivalence claim",
            "no cohort, generalizability, LC-causality, or LC-validation claim",
        ],
    }
    if (
        set(payload) != RESULT_FIELDS
        or set(payload["input_lineage"]) != INPUT_LINEAGE_FIELDS
    ):
        raise RuntimeError("internal bilateral result schema is not exact")
    return _json_safe(payload)


def main():
    parser = argparse.ArgumentParser(
        description=(
            "Run the HUP138 participant-level scalp-only F3/F4 sensitivity"))
    parser.add_argument("--inventory", default=DEFAULT_SCALP_INVENTORY)
    parser.add_argument("--qc-grid", default=DEFAULT_QC_GRID)
    parser.add_argument("--ieeg-cache", default=DEFAULT_IEEG_CACHE)
    parser.add_argument("--scalp-cache", default=DEFAULT_SCALP_CACHE)
    parser.add_argument("--output-dir", default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    payload = build_payload(
        inventory_path=args.inventory,
        qc_grid_path=args.qc_grid,
        ieeg_cache_dir=os.path.abspath(args.ieeg_cache),
        scalp_cache_dir=os.path.abspath(args.scalp_cache),
    )
    _write_artifacts(payload, args.output_dir)
    print(
        f"{SUBJECT} bilateral scalp-only exploratory result -> "
        f"{os.path.abspath(args.output_dir)}",
        flush=True,
    )


if __name__ == "__main__":
    main()
