"""Quarantined legacy 3A/3B/3D summary.

The JSON in ``outputs/cohort_stages_3ABD`` was generated by superseded estimators: a single-bin
3A test, a stage-mismatched 3B null, and continuous-time 3D PAC rather than independent events.
Keeping an executable summarizer made those withdrawn values look current.

Use:
  * ``summarize_corrected_3AB.py`` after complete versioned 3A/3B reruns; and
  * ``summarize_event_3D.py`` after a complete versioned event-3D rerun.
"""
raise SystemExit(
    "LEGACY RESULTS QUARANTINED: outputs/cohort_stages_3ABD must not be analyzed or cited. "
    "Rebuild the versioned caches/results and use summarize_corrected_3AB.py and "
    "summarize_event_3D.py.")
